
CREATE TABLE "Executions" (
  exe_id INT GENERATED BY DEFAULT AS IDENTITY,
  trade_id INT,
  account_number INT,
  order_number BIGINT,
  time_of_execution TIME,
  quantity_executed INT,
  price_executed NUMERIC(10,5),
  PRIMARY KEY(exe_id)
);