
CREATE TABLE "TradeList" (
  trade_id INT GENERATED BY DEFAULT AS IDENTITY,
  pattern_name VARCHAR(40),
  ticker VARCHAR(6),
  exchange VARCHAR(6),
  trade_type VARCHAR(5),
  approx_float BIGINT,
  SSS_PP INT,
  SSS_RR INT,
  SSS_EE INT,
  SSS_PF INT,
  SSS_TS INT,
  SSS_RC INT,
  SSS_ME INT,
  q1 VARCHAR(3),
  q2 VARCHAR(3),
  q3 VARCHAR(3),
  q4 VARCHAR(3),
  PRIMARY KEY(trade_id)
);

CREATE TABLE "Orders" (
  trade_id INT,
  account_number INT,
  order_number BIGINT,
  action VARCHAR(4),
  submit_date DATE,
  exe_type VARCHAR(3),
  requested_price NUMERIC(10,5),
  status VARCHAR(20),
  qty_requested INT,
  PRIMARY KEY(account_number, order_number),
  CONSTRAINT UC_order UNIQUE(trade_id,order_number)
);

CREATE TABLE "Executions" (
  exe_id INT GENERATED BY DEFAULT AS IDENTITY,
  trade_id INT,
  account_number INT,
  order_number BIGINT,
  time_of_execution TIME,
  quantity_executed INT,
  price_executed NUMERIC(10,5),
  PRIMARY KEY(exe_id)
);

ALTER TABLE "Orders" 
ADD FOREIGN KEY(trade_id) REFERENCES "TradeList"(trade_id);

ALTER TABLE "Executions"
ADD FOREIGN KEY(account_number,order_number) 
REFERENCES "Orders"(account_number,order_number);

ALTER TABLE "Executions"
ADD FOREIGN KEY(trade_id)
REFERENCES "TradeList"(trade_id);
